apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-modern-starter
spec:
  displayName: Modern Starter
  author:
    name: Halo
    website: https://github.com/halo-dev
  description: A development starter theme with Vite Ecosystem for Halo
  logo: https://www.halo.run/logo
  homepage: https://github.com/halo-dev/theme-modern-starter#readme
  repo: https://github.com/halo-dev/theme-modern-starter
  issues: https://github.com/halo-dev/theme-modern-starter/issues
  settingName: "theme-modern-starter-setting"
  configMapName: "theme-modern-starter-configMap"
  version: "1.0.0"
  requires: "2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/theme-modern-starter/blob/main/LICENSE"
